version: '2'
services:
    avaliacao360ericb-app:
        image: avaliacao360ericb
        external_links:
            - avaliacao360ericb-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/avaliacao360ericb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avaliacao360ericb-postgresql:
        extends:
            file: postgresql.yml
            service: avaliacao360ericb-postgresql
