---
path: .
instances: 1
buildpack: https://github.com/cloudfoundry/java-buildpack
services:
- avaliacao360ericb
applications:
- name: avaliacao360ericb
  env:
    SPRING_PROFILES_ACTIVE: prod, cloudfoundry
